sudo: required

services:
  -docker

before_install:
  - docker build -t ashishmalgawa/react-test:notry -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true ashishmalgawa/react-test:notry npm test 

after_success:

  - docker build -t ashishmalgawa/multi-client:notry ./client
  - docker build -t ashishmalgawa/multi-server:notry ./server
  - docker build -t ashishmalgawa/multi-worker:notry ./worker
  - docker build -t ashishmalgawa/multi-nginx:notry ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ashishmalgawa/multi-nginx:notry
  - docker push ashishmalgawa/multi-worker:notry
  - docker push ashishmalgawa/multi-server:notry
  - docker push ashishmalgawa/multi-client:notry